/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project33;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Black2
 */
public class Project33 extends javax.swing.JFrame {

    /**
     * Creates new form Project33
     */
    public Project33() {
        initComponents();
    }
    public void GetCurrentDateAndTime()
    {
        Date date = Calendar.getInstance().getTime();
        //Convert the date into Months/days/years/hours/minutes/seconds/
        SimpleDateFormat cDate = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss.");
        String CurrentDate = cDate.format(date);
        char [] array = CurrentDate.toCharArray();
        String dataTaken = new String();
        for(int i=0;i<array.length;i++)
        {
            if(array[i]=='/')
            {
                if(i==2)
                {
                    this.jTextPaneMonth.setText(dataTaken);
                    dataTaken = "";
                }
                else if(i==5)
                {
                    this.jTextPaneDay.setText(dataTaken);
                    dataTaken = "";
                }
            }
            else if(array[i] == ' ')
            {
                this.jTextPaneYear.setText(dataTaken);
                dataTaken="";
            }
            else if(array[i]==':')
            {
                if(i==13)
                {
                    this.jTextPaneHours.setText(dataTaken);
                    dataTaken="";
                }
                else if(i==16)
                {
                    this.jTextPaneMinutes.setText(dataTaken);
                    dataTaken="";
                }
                   
            }
            else if(array[i]=='.')
            {
                this.jTextPaneSeconds.setText(dataTaken);
                dataTaken="";
            }
            else
            {
                dataTaken += Character.toString(array[i]);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPaneHours = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPaneMinutes = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPaneSeconds = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPaneDay = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextPaneMonth = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextPaneYear = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TimeAndDate");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jTextField1.setBackground(new java.awt.Color(102, 102, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("MONTH:");
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(0, 153, 153));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("YEAR:");
        jTextField2.setEnabled(false);

        jTextField3.setBackground(new java.awt.Color(153, 0, 153));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("DAY:");
        jTextField3.setEnabled(false);

        jTextField4.setBackground(new java.awt.Color(255, 0, 51));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("hours:");
        jTextField4.setEnabled(false);

        jTextField5.setBackground(new java.awt.Color(0, 153, 51));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("minutes:");
        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setBackground(new java.awt.Color(0, 102, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("seconds:");
        jTextField6.setEnabled(false);

        jTextPaneHours.setEditable(false);
        jTextPaneHours.setBackground(new java.awt.Color(255, 0, 51));
        jTextPaneHours.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextPaneHours.setFont(new java.awt.Font("Square721 BT", 0, 44)); // NOI18N
        jTextPaneHours.setToolTipText("");
        jTextPaneHours.setAutoscrolls(false);
        jTextPaneHours.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPaneHours.setEnabled(false);
        jTextPaneHours.setFocusCycleRoot(false);
        jTextPaneHours.setFocusable(false);
        jTextPaneHours.setHighlighter(null);
        jTextPaneHours.setOpaque(false);
        jScrollPane6.setViewportView(jTextPaneHours);

        jTextPaneMinutes.setEditable(false);
        jTextPaneMinutes.setBackground(new java.awt.Color(0, 204, 0));
        jTextPaneMinutes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextPaneMinutes.setFont(new java.awt.Font("Square721 BT", 0, 44)); // NOI18N
        jTextPaneMinutes.setToolTipText("");
        jTextPaneMinutes.setAutoscrolls(false);
        jTextPaneMinutes.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPaneMinutes.setEnabled(false);
        jTextPaneMinutes.setFocusCycleRoot(false);
        jTextPaneMinutes.setFocusable(false);
        jTextPaneMinutes.setHighlighter(null);
        jTextPaneMinutes.setOpaque(false);
        jScrollPane7.setViewportView(jTextPaneMinutes);

        jTextPaneSeconds.setEditable(false);
        jTextPaneSeconds.setBackground(new java.awt.Color(0, 102, 204));
        jTextPaneSeconds.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextPaneSeconds.setFont(new java.awt.Font("Square721 BT", 0, 44)); // NOI18N
        jTextPaneSeconds.setToolTipText("");
        jTextPaneSeconds.setAutoscrolls(false);
        jTextPaneSeconds.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPaneSeconds.setEnabled(false);
        jTextPaneSeconds.setFocusCycleRoot(false);
        jTextPaneSeconds.setFocusable(false);
        jTextPaneSeconds.setHighlighter(null);
        jTextPaneSeconds.setOpaque(false);
        jScrollPane8.setViewportView(jTextPaneSeconds);

        jTextPaneDay.setEditable(false);
        jTextPaneDay.setBackground(new java.awt.Color(255, 0, 255));
        jTextPaneDay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextPaneDay.setFont(new java.awt.Font("Square721 BT", 0, 44)); // NOI18N
        jTextPaneDay.setToolTipText("");
        jTextPaneDay.setAutoscrolls(false);
        jTextPaneDay.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPaneDay.setEnabled(false);
        jTextPaneDay.setFocusCycleRoot(false);
        jTextPaneDay.setFocusable(false);
        jTextPaneDay.setHighlighter(null);
        jTextPaneDay.setOpaque(false);
        jScrollPane9.setViewportView(jTextPaneDay);

        jTextPaneMonth.setEditable(false);
        jTextPaneMonth.setBackground(new java.awt.Color(204, 204, 0));
        jTextPaneMonth.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextPaneMonth.setFont(new java.awt.Font("Square721 BT", 0, 44)); // NOI18N
        jTextPaneMonth.setToolTipText("");
        jTextPaneMonth.setAutoscrolls(false);
        jTextPaneMonth.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPaneMonth.setEnabled(false);
        jTextPaneMonth.setFocusCycleRoot(false);
        jTextPaneMonth.setFocusable(false);
        jTextPaneMonth.setHighlighter(null);
        jTextPaneMonth.setOpaque(false);
        jScrollPane10.setViewportView(jTextPaneMonth);

        jTextPaneYear.setEditable(false);
        jTextPaneYear.setBackground(new java.awt.Color(0, 204, 255));
        jTextPaneYear.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextPaneYear.setFont(new java.awt.Font("Square721 BT", 0, 44)); // NOI18N
        jTextPaneYear.setToolTipText("");
        jTextPaneYear.setAutoscrolls(false);
        jTextPaneYear.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPaneYear.setEnabled(false);
        jTextPaneYear.setFocusCycleRoot(false);
        jTextPaneYear.setFocusable(false);
        jTextPaneYear.setHighlighter(null);
        jTextPaneYear.setOpaque(false);
        jScrollPane11.setViewportView(jTextPaneYear);

        jLabel1.setFont(new java.awt.Font("Square721 BT", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(":");

        jLabel2.setFont(new java.awt.Font("Square721 BT", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(":");

        jLabel3.setFont(new java.awt.Font("Square721 BT", 0, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("-");

        jLabel4.setFont(new java.awt.Font("Square721 BT", 0, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Project33 obj = new Project33();
        Timer timer = new Timer(1000, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                obj.GetCurrentDateAndTime();
            }
        });
        timer.setRepeats(true);
        timer.setCoalesce(true);
        timer.start();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project33.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project33.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project33.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project33.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                //new Project33().setVisible(true);
                obj.setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextPane jTextPaneDay;
    private javax.swing.JTextPane jTextPaneHours;
    private javax.swing.JTextPane jTextPaneMinutes;
    private javax.swing.JTextPane jTextPaneMonth;
    private javax.swing.JTextPane jTextPaneSeconds;
    private javax.swing.JTextPane jTextPaneYear;
    // End of variables declaration//GEN-END:variables
}
